# Generated by Django 6.0 on 2026-04-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('game_name', models.CharField(max_length=100)),
                ('time_played', models.CharField(max_length=20)),
                ('start_balance', models.FloatField()),
                ('end_balance', models.FloatField()),
                ('profit', models.FloatField(blank=True, null=True)),
                ('spins', models.IntegerField()),
                ('bet', models.FloatField()),
                ('best_win', models.FloatField()),
                ('bonus_buy', models.BooleanField(default=False)),
                ('spin_mode', models.CharField(max_length=50)),
                ('video_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
